id: P004470
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG12213
  title: གུ་རུའི་གའུ་བདུན་མ།
  author: ''
  volumes:
    a7fd5d46d61e4484a3094bd6dc4eb3ee:
      image_group_id: I1KG12232
      title: ''
      volume_number: 1
      total_pages: 164
      base_file: v001.txt
