id: IA4D88178
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T17:18:20+00:00'
last_modified: '2022-06-08T01:18:52.420358+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12213
  title: གུ་རུའི་གའུ་བདུན་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9E92:
      image_group_id: I1KG12232
      title: ''
      total_pages: 164
      order: 1
      base_file: 9E92.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
